Added API check for GSMA channel

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -198,6 +198,19 @@ jobs:
               exit 1
             fi
             pkill kubectl
+      - run:
+          name: Validate GSMA Connector Api Endpoint
+          command: |
+            echo "Validate GSMA Connector Api Endpoint"
+            kubectl -n ${CHART_NAMESPACE} port-forward service/ph-ee-connector-gsma 15000:80 & sleep 5
+            response=$(curl -w "<->%{http_code}" --location 'http://127.0.0.1:15000')
+            response_code=$(echo $response | awk -F"<->" '{print $2}')
+            response_body=$(echo $response | awk -F"<->" '{print $1}')
+            if [ "$response_code" != "200" ] || [ "$response_body" != "GET Good" ]; then
+              echo "GSMA Connector Api Endpoint test failed!"
+              exit 1
+            fi
+            pkill kubectl
             
 parameters:
   deploy_allowed:
